<?php

namespace AppBundle\Repository;

/**
 * en_translationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class en_translationRepository extends \Doctrine\ORM\EntityRepository
{
}
