<?php

namespace AppBundle\Repository;

/**
 * fr_translationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class fr_translationRepository extends \Doctrine\ORM\EntityRepository
{
}
